---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: emr-eks-example
  region: ap-southeast-2
  tags:
    Owner: jaehyeon

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: m5.xlarge
